paths:
  /products/product/{pid}:
    get:
      summary: Gets the product with the given id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: Path parameter that takes the product id
          required: true
          type: string
      responses:
        "200":
          description: The product with the given id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Product not found Error

    put:
      summary: Update the product with the given id and data from req.body
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: Path parameter that takes the product id
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: Product updated successfully
        "404":
          description: Product not found Error
        "401":
          description: Unauthorized Error

    delete:
      summary: Deletes the product with the given id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: Path parameter that takes the product id
          required: true
          type: string
      responses:
        "204":
          description: Product deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Product not found Error
        "401":
          description: Unauthorized Error